### ISSUE TITLE
no.... :-{

### ISSUE THREAD

**Issue by ali-libre** [takke/DataStats#1]
it dont work...
why...?
galaxytab 10.1 android kikat 4.4

**Comment by takke** [comment]
how it does not work?

tell me your screenshot.

**Comment by ali-libre** [comment]
it showed on top of screen & preview are work good..
but does'nt monitor real rate...  no wifi no gsm...

**Comment by takke** [comment]
Maybe it's relating to this issue: https://code.google.com/p/android/issues/detail?id=19938

hmm, I don't have real galaxytab 10.1 device so I can't support...

**Comment by ali-libre** [comment]
why issue not placed in github
ihavent access google

**Comment by takke** [comment]
are you using any custom rom?

i think that the behavior is the problem of custom rom or device.

**Comment by ali-libre** [comment]
this means than everyone use custum rom cant use this...!
so bad...
good look...
