### ISSUE TITLE
What does the interpolate mode do exactly?

### ISSUE THREAD

**Issue by revuwa** [takke/DataStats#11]
This is not an usual issue, it's more a question.

You commited this: https://github.com/takke/DataStats/commit/186c586aa4161f8727497247f62a166a103d32c2 to you project and I don't understand exactly, what's the benefit from that change. So I kindly wanted to ask for that.

On https://play.google.com/store/apps/details?id=jp.takke.datastats you wrote:
"Add interpolation mode (Notice decreasing your battery life)"
Does this mean, that my battery will be empty faster when this feature is set? 
Or that this feature saves battery power - and if so, would you please tell me why (theoretically)? 
Is this just a battery saving calculation method?

Thanks in advance for any response and by the way, thanks for your enthusiasm to make and share such a cool & useful tool like DataStats!

**Comment by takke** [comment]
Are you tried the interpolate mode?
(You'll be able to see the exact feature of that...)

In other words, the interpolate mode is like a "animation mode".
When the app captures traffics every seconds, it draws animated graph by interpolated values.

So in the interpolate mode, it drains more battery because the frequency(refresh-rate) is higher than normal mode.

> Does this mean, that my battery will be empty faster when this feature is set?

may be yes.

> Is this just a battery saving calculation method?

no.

**Comment by revuwa** [comment]
> Are you tried the interpolate mode?
> (You'll be able to see the exact feature of that...)

Yes, several times, but I can't see any difference - that's the reason why I'm asking.

> In other words, the interpolate mode is like a "animation mode".
> When the app captures traffics every seconds, it draws animated graph by interpolated values.

Hmm, I show you what I see:
# With 'interpolate mode' on
![interpol](https://cloud.githubusercontent.com/assets/7300276/6979899/6a4afdac-d9ea-11e4-8271-3eb0c5dc926c.png)
![interpol_pref](https://cloud.githubusercontent.com/assets/7300276/6979894/55549dc2-d9ea-11e4-856e-e4a3edd054e3.png)
# With 'interpolate mode' off
![no-interpol](https://cloud.githubusercontent.com/assets/7300276/6979904/771a4218-d9ea-11e4-835e-e83b447d5f65.png)
![no-interpol_pref](https://cloud.githubusercontent.com/assets/7300276/6979902/747c3ade-d9ea-11e4-9171-ef9f0e95fae0.png)

And there is no noticeable difference between the refresh rates; both modes refreshes in absolutely the same interval-cycle.

After switching the modes, I [Stop]ped and [Start]ed the DataStats-service round about thousand times.

Could this be a problem depending on my device/platform:
* Samsung Galaxy S2 (I9100) (@ 480x800 pixel resolution)
* AOSP 4.2.2

like this little glitch:

![preview](https://cloud.githubusercontent.com/assets/7300276/6979997/d3952fe8-d9eb-11e4-91dd-387c1802b734.png)
or do I still just don't get what you trying to explain?

**Comment by takke** [comment]
Animation DEMO of interpolate mode:

https://www.youtube.com/watch?v=XhF7GgOzRLY

How about in your device?

**Comment by revuwa** [comment]
Now I think I know what's going on.
If I enable the [X] Logarith bar, then I see the difference in the smoothness of the colored bar-meter, but the refresh rate of the numbers keeps the same.
Because I've disabled the [_] Logarith bar, I can't see any difference.

So it might be an idea to make the [_] Interpolate option depending on an enabled [_] Logarith bar, because IMHO there is no benefit for the numbers-only view, or am I wrong?

Thanks for your time and your helpful video link!
And thanks again for your enthusiasm and this brilliant app!

**Comment by takke** [comment]
> So it might be an idea to make the [X] Interpolate option depending on an enabled [X] Logarith bar, because IMHO there is no benefit for the numbers-only view, or am I wrong?

That's right and good idea to me!

So I implemented and I'll release with this fix:

https://github.com/takke/DataStats/commit/654329be99023e44bfea7b90c30097ba34bbe7f6

**Comment by xa4hf8** [comment]
Should look like this:
___
☐ Logarithmic scale

☐ Animate graph (smooth transitions)🪫
___
It is probably not even necessary to mention increased battery usage because the difference is not noticeable on newer devices.
