### ISSUE TITLE
wanna change the app-icon?

### ISSUE THREAD

**Issue by revuwa** [takke/DataStats#14]
I saw a <slightly> similar-looking logo in a Microsoft® product called Lync™ (or Skype for Business™):
![image](https://cloud.githubusercontent.com/assets/7300276/7498112/bf31dedc-f41e-11e4-88d3-a1129c58a8b7.png)
which is a communication software. So I thought DataStats could possibly change its icon to a more "up" and "down" oriented symbol, if you want to do so.

Please don't get me wrong. I like your logo; this is just the first thing I thought, as I saw the other tray-icon.

**Comment by revuwa** [comment]
If you like, there're some online icon creation tools out there.

For example: https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
Which is- and uses open source code and cliparts...

With a few clicks you get something like this:
![ic_launcher](https://user-images.githubusercontent.com/7300276/30335816-9a528bf0-97e3-11e7-89bc-ed114325805b.png)
or this (if you stick on the current style, but want to update the icon, anyway):
![ic_launcher](https://user-images.githubusercontent.com/7300276/30336334-294af4fe-97e5-11e7-9b72-ba468fc1e1ab.png)
and the complete "ic_launcher.zip" (with hdpi/mdpi/xhdpi/xxhdpi/xxxhdpi resolution icons) as download.

**Comment by takke** [comment]
Thanks @revuwa !

I'll replace the app icon as below.

![ic_launcher](https://user-images.githubusercontent.com/73930/107604298-0cfedc00-6c73-11eb-8b50-515bf684dbe3.png)

https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=import_export&foreground.space.trim=1&foreground.space.pad=0.15&foreColor=rgb(139%2C%20195%2C%2074)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=circle&effects=elevate&name=ic_launcher
