### ISSUE TITLE
Logarithm bar misbehavior

### ISSUE THREAD

**Issue by revuwa** [takke/DataStats#16]
I don't want to us the point [_] Logarithm bar, so I disabled that checkbox.

But on higher data transfers, I still see a shorter version of the regular logarithm bar. To show what I mean I've made 3 (merged) screenshots:
![screens](https://cloud.githubusercontent.com/assets/7300276/8378222/2d99521c-1c18-11e5-89a0-f3c23bf5bb0b.png)
As you can see, there is no logarithm bar on the white colored data traffic. But on the green traffic there comes up a little bar. On the red traffic I get a more or less regular logarithm bar, while that point is definitely disabled.

It's not a big deal. But I hope, it's an interesting information for you, anyway.

**Comment by takke** [comment]
When you disable the Logarithm bar checkbox, the bar increases mode is "linear".
So you can see some bars like that.
Thanks.
