### ISSUE TITLE
Preview graphic-glitch on 480x800 pixel-resolution

### ISSUE THREAD

**Issue by revuwa** [takke/DataStats#17]
I have a little glitch on my resolution, (which is the highest on my device): 
Samsung Galaxy S2 "I9100" @ 480x800 pixel.
![screens](https://cloud.githubusercontent.com/assets/7300276/6979997/d3952fe8-d9eb-11e4-91dd-387c1802b734.png)
IMHO, because there is a working slider bar, there is no further need for the predefined [XXKB]-buttons.
Removing them, (or reducing them to 2-3 buttons) will prevent such graphic-glitches on smaller devices, too.

What do you think?

**Comment by takke** [comment]
It should be fixed in v2.8.0.

Thanks.
