### ISSUE TITLE
Bug in the interface

### ISSUE THREAD

**Issue by 0liUms** [takke/DataStats#2]
There is things at the bottom but impossible to go down, like a missing scrollbar ?

I'm on a SGS2 running Android 5, perhabs bug is mine ?

**Comment by takke** [comment]
i'll fix.

**Comment by takke** [comment]
Fixed at:
https://github.com/takke/DataStats/commit/95459216d43538ab2936ce4e5b0f64e84b88d778

I'll release soon...
