### ISSUE TITLE
installing apk

### ISSUE THREAD

**Issue by ali-libre** [takke/DataStats#6]
Abnormal issue!
When your monitor installed install bottun of apk installer will not work...!
I tested it on tow rom...!!

**Comment by takke** [comment]
fixed at latest version.
check app version and tell me.
thanks

**Comment by ali-libre** [comment]
I have last version 1.21...
ofcourse i havent no problem with scroll

**Comment by takke** [comment]
ok, so i can't support your rom.
that is just a restriction for the rom.
