### ISSUE TITLE
Meters offset from screen border in landscape mode

### ISSUE THREAD

**Issue by phirsch** [takke/DataStats#7]
In portrait mode, the meters are positioned flush with the top border of the content area (right below the status bar). In landscape mode, however, they are offset from the top border, causing them to appear a little more intrusive.

**Comment by takke** [comment]
Can you show me the screenshot?
and tell me your device name or spec.

**Comment by phirsch** [comment]
Sorry, forgot to mention that it only happens when the status bar is hidden in immersive/full screen mode, e.g. within YouTube. Do you still need a screenshot? Would have to find out how to attach one...

**Comment by takke** [comment]
OK IC, but it's just a spec currently.

Of course i'm always waiting for your pull request :smiley:

**Comment by takke** [comment]
Fixed https://github.com/takke/DataStats/commit/513680ebd7a2366e880fcf41fd2a4f4312500945

**Comment by phirsch** [comment]
Thanks for the quick fix! However, I'd actually like the meters to stay visible in full screen as well (or have this as a preference), but I'd prefer them to be right at the top border of the screen.

**Comment by takke** [comment]
Fixed https://github.com/takke/DataStats/commit/ecbcf8d4879370d4870b5cd699e17457996ca858

Please try this:
https://www.dropbox.com/s/9aluk9yvrr9avgi/DataStats_123_20150219_1753.apk?dl=0
