### ISSUE TITLE
Unable to install/update apps when active

### ISSUE THREAD

**Issue by grote** [takke/DataStats#9]
Thanks for this great and useful app! :)

Unfortunately, I am unable to install/update apps from F-Droid when it is active. I see the screen showing me the permissions of the app, but can not click on 'Install'. Looks like the touch event is not registered maybe because of the way DataStats overlays the screen.

When disabling DataStats, I can click the Install button just fine.

**Comment by takke** [comment]
same issue? #3

**Comment by grote** [comment]
Yes, that sounds like the same issue. Now we need only a new release with this fix.

**Comment by takke** [comment]
already released. please try it.

**Comment by grote** [comment]
It has just hit F-Droid. Tested successfully. You can close this now. Thanks!

**Comment by takke** [comment]
thanks.
